### ISSUE TITLE
install php8.2 show icu4c version error

### ISSUE THREAD

**Issue by greezen** [shivammathur/homebrew-php#2408]
**Describe the bug**

after install php8.2 use `brew install shivammathur/php/php@8.2`, run `php -v`, has the  error
php: error while loading shared libraries: libicuio.so.73: cannot open shared object file: No such file or directory
**PHP versions**

php8.2 & php8.1

**To Reproduce**

**Expected behavior**

**Screenshots/Logs**

**Additional context**

php: error while loading shared libraries: libicuio.so.73: cannot open shared object file: No such file or directory

**Are you willing to submit a PR?**

**Comment by webard** [comment]
`brew upgrade` causes php not work with error above, tested 8.2 and 8.3.

**Comment by webard** [comment]
Works after installing latest version.

**Comment by greezen** [comment]
run reinstall is work for me, don't now what happen
```shell
brew reinstall shivammathur/php/php@8.1
```

**Comment by shivammathur** [comment]
All builds completed with the new icu4c version, so reinstalling the PHP version should fix the issue.

**Comment by HapiCZ** [comment]
the problem persists if the pecl_http package is installed:
issue: https://github.com/shivammathur/homebrew-extensions/issues/3795
